<?php
/** @var MageMontreal\CategoryWidget\Block\Widget\CategoryWidget $block */

$grouped_categories = $block->getAlphabetGrouped();
?>

<div class="mm-category-widget mm-category-widget-<?= $block->getType() ?>">
    <div class="product data items"
         data-mage-init='{"mage/tabs": {"openedState": "active", "collapsibleElement":".-title", "content":".-content","trigger":".-trigger", "animate": {"duration": 100}, "disabledState": "disabled"}}'>
        <?php $i=0; foreach ($grouped_categories as $group_name => $group): $i++ ?>
            <div class="item title -title">
                <a class="switch -trigger" href="#tab-cat-<?= $i ?>"><?= $block->escapeHtml($group_name) ?></a>
            </div>
            <div id="tab-cat-<?= $i ?>" class="item content -content">
                <div class="list-content">
                    <?php foreach ($group as $letter => $categories): ?>
                        <div class="group-content">
                            <h3 class="top-letter"><?= $block->escapeHtml($letter) ?></h3>
                            <div class="categories-content">
                                <?php foreach ($categories as $category): ?>
                                    <div>
                                        <a class="catnav" href="<?= $block->escapeUrl($category->getUrl()) ?>">
                                            <?= $block->escapeHtml($category->getName()) ?>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>