<?php
/** @var MageMontreal\CategoryWidget\Block\Widget\CategoryWidget $block */

$categories = $block->getCategoryCollection();
$canShowImg = $block->canShowImage();
$canShowName = $block->canShowName();
?>

<div class="block-content catalog-category">
    <?php foreach ($categories as $category): ?>
        <div class="category">
            <?php if ($canShowImg && $category->getImageUrl()): ?>
                <div class="category-image">
                    <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
                        <img src="<?php echo $block->escapeUrl($category->getImageUrl()) ?>" alt="<?php echo $block->escapeHtml($category->getName()) ?>" width="<?= $this->getImageWidth() ?>" height="<?= $this->getImageHeight() ?>"/>
                    </a>
                </div>
            <?php endif;?>
            <?php if ($canShowName): ?>
                <div class="category-name">
                    <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
                        <?php echo $block->escapeHtml($category->getName()) ?>
                    </a>
                </div>
            <?php endif;?>
        </div>
    <?php endforeach; ?>
</div>